### ISSUE TITLE
issues on running flutter cell info with iOS

### ISSUE THREAD

**Issue by Cescito04** [devSumanrazz/flutter_cell_info#2]
Flutter cell info is working on android but there's an this issue for iOS with flutter

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method cell_info on channel cell_info)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
<asynchronous suspension>
#1      CellInfo.getCellInfo (package:flutter_cell_info/flutter_cell_info.dart:9:29)
<asynchronous suspension>
#2      _SpeedTestState.initPlatformState (package:qosambassadors/screens/speedtest.dart:1104:33)
<asynchronous suspension>

**Comment by Cescito04** [comment]
Someone can help please

**Comment by azazadev** [comment]
@Cescito04 I've noticed that this package claims to support iOS on pub.dev, but it doesn't actually provide iOS functionality. From my experience, the package isn't implemented for iOS, which is surprising given that it's listed as supported.

I'm currently working on an internal application that needs to collect cell information, and it won't be published to the Apple Store. Due to the deprecation of CoreTelephony, this package doesn't work on iOS.

It's misleading for the package owner to claim iOS support when it hasn't been implemented. If anyone finds an alternative solution that works on iOS, please share it with the community. Your help would be greatly appreciated.

**Comment by famasf1** [comment]
This lib actually forked from https://pub.dev/packages/cell_info which is like 3 years old as the time of writing. And seems like all the forked owner does is fixing example so he can run it.


My bet is the owner of this forked probably have no idea how to fix this either. The original owner of the fork [here](https://github.com/eslamfaisal/FlutterCellInfo) didn't implemented it on iOS. And the original API that both of these lib wrapped https://github.com/mroczis/netmonster-core specifically aimed only on Android.

It seems like no-one is currently doing an implementation of CallKit at the moment. So it might be time to brush your Swift knowledge and implementing it from MethodChannel yourself. I'll fork this lib and tried on my end. Here's hoping that it won't be too much work.

**Comment by sumanrajpathak** [comment]
> This lib shamelessly forked from https://pub.dev/packages/cell_info which is like 3 years old as the time of writing. And seems like all the forked owner does is fixing example so he can run it.
> 
> My bet is the owner of this forked probably have no idea how to fix this either. The original owner of the fork [here](https://github.com/eslamfaisal/FlutterCellInfo) didn't implemented it on iO. And the original API that both of these lib wrapped https://github.com/mroczis/netmonster-core specifically aimed only on Android.
> 
> It seems like no-one is currently doing an implementation of CallKit at the moment. So it might be time to brush your Swift knowledge and implementing it from MethodChannel.

We are currently working on IOS implementation. Yes, this is a fork from cell_info and credit has been given to original author please refer to readme . This plugin is released to support the latest version of flutter.

**Comment by Cescito04** [comment]
> This lib actually forked from https://pub.dev/packages/cell_info which is like 3 years old as the time of writing. And seems like all the forked owner does is fixing example so he can run it.
> 
> My bet is the owner of this forked probably have no idea how to fix this either. The original owner of the fork [here](https://github.com/eslamfaisal/FlutterCellInfo) didn't implemented it on iOS. And the original API that both of these lib wrapped https://github.com/mroczis/netmonster-core specifically aimed only on Android.
> 
> It seems like no-one is currently doing an implementation of CallKit at the moment. So it might be time to brush your Swift knowledge and implementing it from MethodChannel yourself. I'll fork this lib and tried on my end. Here's hoping that it won't be too much work.

hello Sir, please show how do you implement it form MethodChannel

**Comment by xdkomel** [comment]
> This lib actually forked from https://pub.dev/packages/cell_info which is like 3 years old as the time of writing. And seems like all the forked owner does is fixing example so he can run it.
> 
> My bet is the owner of this forked probably have no idea how to fix this either. The original owner of the fork [here](https://github.com/eslamfaisal/FlutterCellInfo) didn't implemented it on iOS. And the original API that both of these lib wrapped https://github.com/mroczis/netmonster-core specifically aimed only on Android.
> 
> It seems like no-one is currently doing an implementation of CallKit at the moment. So it might be time to brush your Swift knowledge and implementing it from MethodChannel yourself. I'll fork this lib and tried on my end. Here's hoping that it won't be too much work.

I think the iOS implementation won't ever be available cause the OS never allowed collecting cell info. There's even no such kind of a permission like phone state, cell data, etc. CallKit is a whole different story and it wouldn't allow for cell info either.

**Comment by sumanrajpathak** [comment]
IOS implementation is complete. I will be closing the issue, if you face any error regarding the IOS please report with new issue
