### ISSUE TITLE
Error Example Apps

### ISSUE THREAD

**Issue by DenisMrGnusa** [devSumanrazz/flutter_cell_info#3]
Hello @sumanrajpathak thank you for your plugin, I am currently trying this plugin. but have a problem that the example application you provide does not display any data, and there is an error as follows:

`E/MethodChannel#cell_info(20970): Failed to handle method call
E/MethodChannel#cell_info(20970): java.lang.SecurityException: getDataNetworkTypeForSubscriber
E/MethodChannel#cell_info(20970): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
E/MethodChannel#cell_info(20970): 	at android.os.Parcel.createException(Parcel.java:3041)
E/MethodChannel#cell_info(20970): 	at android.os.Parcel.readException(Parcel.java:3024)
E/MethodChannel#cell_info(20970): 	at android.os.Parcel.readException(Parcel.java:2966)`

I hope with this report I can help in the development of this plugin.
Best regards

**Comment by xdkomel** [comment]
Hey! The issue is due to insufficient permissions. You have to give the example app phone state permission manually or ask for it in MainActivity. It asks for `READ_EXTERNAL_STORAGE` in the example which is incorrect.

**Comment by xdkomel** [comment]
I've fixed this problem in my fork and updated the `build.gradle` if you need an out of the box solution: https://github.com/xdkomel/flutter_cell_info_plugin. You can also contact me in case of questions

**Comment by sumanrajpathak** [comment]
@xdkomel Can you open a PR for the fixes, i would like to update with your changes included in the next release
